### PR TITLE
Installation instructions.

### PR DESCRIPTION
**Pull request by serranoarevalo**

### CODE REVIEW

**Comment by ai** [comment]
Not sure that `--save-dev` is ideal case for everyone

**Comment by ThiefMaster** [comment]
Hey @ai, when would you not want this in your devDependencies? From what I can see this doesn't result in any runtime code.

**Comment by ThiefMaster** [comment]
OK, so just edge cases. Might be better to use `--save-dev` in the readme (the yarn command there uses `--dev` btw)

**Comment by ai** [comment]
I think in this case user should understand what they is doing. So it is better not to recommend any command.

Anyway the whole installing instruction is the case 😄

**Pull request merged**
